services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=price'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
